function (err) {
		finish(err, 'callback');
	}